apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  hostNetwork: true
  containers:
    - name: web
      image: nginx
      ports:
        - name: web-http
          containerPort: 80
          protocol: TCP
        - name: web-https
          containerPort: 443 
          protocol: TCP
      volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        name: nginx-conf
      - mountPath: /etc/letsencrypt
        name: etc-letsencrypt
  volumes:
  - name: etc-letsencrypt
    hostPath:
      path: '/etc/letsencrypt'
      type: 'DirectoryOrCreate'
  - name: nginx-conf
    hostPath:
      path: '/etc/nginx/nginx.conf'
      type: 'FileOrCreate'
