"        _
" __   _(_)_ __ ___  _ __ ___
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__
" (_)_/ |_|_| |_| |_|_|  \___|
"

let mapleader = ','

filetype plugin indent on
syntax on

set ruler
set showcmd
set hidden
set wildmenu
set wildoptions=pum
set incsearch
set hlsearch
set splitright
set splitbelow
set laststatus=2
set expandtab smarttab          " Use spaces instead of tabs, but make it _feel_ like tabs
set softtabstop=-1              " Use value of 'shiftwidth' to determine indent size
set path=.
set path+=**
set wildignore=*/.git/*,*/venv/*,*.pyc,*/__pycache__/*,*/node_modules/*
set regexpengine=0
set foldlevelstart=99           " Start with all folds open
set backspace=indent,eol,start  " backspace works like other programs
set background=dark             " Make sure colours aren't weird when using a dark terminal theme
set mouse=nv                    " No mouse in insert mode 
set autoindent


nnoremap Y y$
nnoremap <silent> <Leader>l :nohlsearch<CR>

nnoremap j gj
nnoremap k gk

" Quickly switch buffers - https://vi.stackexchange.com/a/2187
nnoremap <Leader>b :ls<CR>:b<Space>

" Quckly fuzzy search for files
nnoremap <Leader>e :e **/*

" Netrw (file browser)

let g:netrw_altfile=1     " CTRL-^ never goes to netrw
let g:netrw_banner=0      " No banner
let g:netrw_liststyle=3   " Tree style
nnoremap - :Explore<CR>



" Install vim-plug if not found
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'

" Initialize plugin system
" - Automatically executes `filetype plugin indent on` and `syntax enable`.
call plug#end()

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" vim: fdm=marker sw=2 fdls=-1
